### ISSUE TITLE
R10 GS Pro ball speed limit 170.5mph 

### ISSUE THREAD

**Issue by JLag1** [travislang/gspro-garmin-connect-v2#8] opened 2022-12-30 21:57 UTC
@travislang 

There are a few people who are only getting a maximum of 170.5mph ball speed and it won't allow them to get any higher. On the Garmin app they are able to get 180+ no problem.

Is there a reason for the limit? And is it something in the transfer of data between the R10 and GS Pro? I have reached out to GS Pro support and they said it's nothing to do their end. 

Cheers

**Comment by travislang** [comment] 2022-12-30 22:11
No, there shouldnt be a limit.  Looking into this now

**Comment by travislang** [comment] 2022-12-30 23:03
I don't see anywhere in this program where I have added any limits, it just takes the data from garmin and passes it to GSPro, can you explain further what you are noticing?

**Comment by JLag1** [comment] 2022-12-31 01:02
So there have been a few people on the Facebook group now that have said they can use the Garmin app on their phone and on the driving range be getting 180+mph ball speed then when they connect and use GS Pro it doesn't go any higher than 170.5mph.

**Comment by travislang** [comment] 2022-12-31 01:15
Any way you can post a link to one of those convos? Just trying to dig further cause I’m not sure that this is caused by this program…

**Comment by JLag1** [comment] 2022-12-31 01:18
Yes I would be surprised if it was that's why I contacted GS Pro support first because I thought it would be their end.. 

https://m.facebook.com/groups/338462847726406/permalink/688895059349848/?mibextid=Nif5oz

**Comment by etogburn** [comment] 2023-02-21 01:31
it looks like this issue has been stagnant for a while, but I did want to chime in. I have the same problem except my ball speed is limited to 170 flat. The exports from GSPro have a number of decimal points except for the ball speeds over 170. The garmin golf app shows that the ball speed was picked up as a valid number that is greater than 170. I just discovered the problem today and will update if I find anything else out. At this point, I have to assume that the garmin golf app is reporting the number greater than 170 and it is getting truncated in either the connection app or in GSPro.

**Comment by alleexx** [comment] 2023-02-21 07:52
I had a look into the connector and from my point of view it is not a problem there and also not on the gspro side. The ball data is just passed through. To verify I increased the test shot to 185 MPH and passed this to gspro. It worked fine and showed up the same in gspro. I would think that the garmin is not posting this correctly in the e6 connect to pc area. Can you validate it by using e6 directly if that is the case. I would think it is and then needs to go to garmin support. Here is a screenshot of the same.

![image](https://user-images.githubusercontent.com/6170254/220281691-5fd6ec51-bf9e-44d2-bc76-e6faaabf3530.png)

**Comment by etogburn** [comment] 2023-02-21 13:01
@alleexx thanks for verifying that! Is there a way I can see the object that's passed from the Garmin app to the connection app? I will try to verify that it is either passing 170 or the actual measure value.

**Comment by alleexx** [comment] 2023-02-21 14:22
You can change the setBallData Function in the garminConnect.js file to this to print the ball speed number as a R10 message in the app. Let me know if it works. I would reproduce it for you but I do not have that speed :)

setBallData(ballData) {
        let spinAxis = Number(ballData.SpinAxis)
        if (spinAxis > 90) {
            spinAxis -= 360
        }
        spinAxis *= -1
        this.ipcPort.postMessage({
            type: 'R10Message',
            message: `R10 Ball Data: ${ballData.BallSpeed}`,
        })
        this.ballData = {
            ballSpeed: ballData.BallSpeed,
            spinAxis: spinAxis,
            totalSpin: ballData.TotalSpin,
            hla: ballData.LaunchDirection,
            vla: ballData.LaunchAngle,
        }

        this.ipcPort.postMessage({
            type: 'gsProShotStatus',
            ready: false,
        })

        this.client.write(SimMessages.get_success_message('SetBallData'))
    }

**Comment by etogburn** [comment] 2023-02-21 14:49
@alleexx Thanks so much. Is there a quick web link you that has build information? I have wanted to experiment with a few other things as well.

**Comment by alleexx** [comment] 2023-02-21 14:57
Well the connect app is a react native app. If you change the js coding it will just use this with the next start. If you want to dig deeper you should clone the code from Travis or my fork with the putting enabled and set up your environment. You would need to have node installed and could then debug the code using vscode for example. You should find what you need looking for react native and node.js. I do not have a one shop link unfortunately. Was this information what you were looking for?

**Comment by etogburn** [comment] 2023-02-21 15:00
Yes, that is exactly what I needed. Thank you

**Comment by alleexx** [comment] 2023-02-21 15:04
Actually looking at it I am not sure if react native is actually used, I thought it was. The packager is electron.js based to run and make the app in the end. You can just look at the package.json and find the information on the correct start and make scripts.

**Comment by etogburn** [comment] 2023-02-21 15:35
I just got off a chat with Garmin R10 support. It sounds like they are denying any fault "If it works in the garmin golf app range, then it works just fine". I want to try to test this with the PC version of E6 too. If I can get my hands on a free trial of E6 for PC, I will try on a range there and see if the issue is present. 

Thanks for looking into the app's framework. I will spend a little time with it this evening and see what values are being received. I'll try to look at each portion. 

Garmin app
garmin app to GSpro connect
gspro connect input to output
gspro connect to gspro (looks like it's verified by your testing)

I want to also test E6 connect and E6 PC version.

I will update with my findings as I have them.

**Comment by etogburn** [comment] 2023-02-22 01:40
![image](https://user-images.githubusercontent.com/10671257/220498711-d320b78c-fde6-48b3-9c6a-2c66959ff737.png)

It looks like the incoming data has the issue. I put the output message in the setBallData function just as you noted above.

**Comment by travislang** [comment] 2023-04-27 19:24
Closing as this isn't a problem with this connection program and lies in the R10 app

**Closed by travislang** 2023-04-27 19:24 UTC
